services:
  - type: web
    name: lingo-voice-backend
    env: python
    plan: free
    region: singapore
    buildCommand: ""
    startCommand: uvicorn main:app --host=0.0.0.0 --port=10000
    envVars:
      - key: PORT
        value: 10000
